import scrapy

class JobItem(scrapy.Item):
    id            = scrapy.Field() 
    title         = scrapy.Field()
    company_name  = scrapy.Field()
    company_sectors = scrapy.Field()
    description   = scrapy.Field()
    contract      = scrapy.Field()
    region        = scrapy.Field()
    education     = scrapy.Field()
    experience    = scrapy.Field()
    skills        = scrapy.Field()
    posted       = scrapy.Field()
    url          = scrapy.Field()
    source       = scrapy.Field()
    metier_type  = scrapy.Field()
    metiers      = scrapy.Field()
    posted       = scrapy.Field()
    scraped_at   = scrapy.Field()
    job_missions = scrapy.Field()
    job_profile  = scrapy.Field()
    job_criteria = scrapy.Field()
    job_skills   = scrapy.Field()
    job_count    = scrapy.Field()


class emploidakar(scrapy.Item):
    id               = scrapy.Field()
    title            = scrapy.Field()
    contract_type    = scrapy.Field()
    location         = scrapy.Field()
    posted_date      = scrapy.Field()
    company_name     = scrapy.Field()
    company_website  = scrapy.Field()
    company_logo     = scrapy.Field()
    description_p    = scrapy.Field()
    description_ul   = scrapy.Field()
    url              = scrapy.Field()
    source           = scrapy.Field()


class emploi_senjob(scrapy.Item):
    id               = scrapy.Field()
    title            = scrapy.Field()
    contract_type    = scrapy.Field()
    location         = scrapy.Field()
    expiration       = scrapy.Field()
    description      = scrapy.Field()
    categorie        = scrapy.Field()
    url              = scrapy.Field()
    source           = scrapy.Field()
    salaire          = scrapy.Field()
    reference        = scrapy.Field()
    posted_date      = scrapy.Field()
    categorie        = scrapy.Field()
    contract_type    = scrapy.Field()



class emploi_expatdakar(scrapy.Item):
    id = scrapy.Field()
    title = scrapy.Field()
    posted_date = scrapy.Field()
    ad_id = scrapy.Field()
    location = scrapy.Field()
    region = scrapy.Field()
    employeur = scrapy.Field()
    secteur = scrapy.Field()
    type_contrat = scrapy.Field()
    niveau = scrapy.Field()
    niveau_etude = scrapy.Field()
    experience = scrapy.Field()
    nb_postes = scrapy.Field()
    description = scrapy.Field()
    url = scrapy.Field()
    source = scrapy.Field()
