version: "3.9"

services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__FERNET_KEY: 'ezN0VbZaIlcTc0WWOy6lA0PAOTRC4n5gFrU-COPFWPI='
      DATABASE_URL: sqlite:////opt/airflow/airflow.db
      PORT: 8080
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      - ./Emploi_senegal:/opt/scrapy_project
    ports:
      - "8080:8080"
    command: bash start.sh
    networks:
      - emploi_network

networks:
  emploi_network:
    driver: bridge

environment:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${DATABASE_URL}
  # pas AIRFLOW__CORE__SQL_ALCHEMY_CONN (déprécié)
  AIRFLOW__CORE__EXECUTOR: SequentialExecutor
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
  AIRFLOW__CORE__FERNET_KEY: 'ezN0VbZaIlcTc0WWOy6lA0PAOTRC4n5gFrU-COPFWPI='


